[build]
  # Publish directory - Netlify will serve files from Web directory
  publish = "Web"
  
  # Build command (optional - we don't need to build static files)
  command = ""

[functions]
  # Directory containing serverless functions
  directory = "netlify/functions"
  # Python runtime will be auto-detected from runtime.txt

# Redirect rules for API endpoints
[[redirects]]
  from = "/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/reset_api"
  to = "/.netlify/functions/reset_api"
  status = 200

# Serve static files - this should come last
# Let Netlify serve HTML files directly from Web directory

